### ISSUE TITLE
[dialog] body scroll happening in iPhone safari browser when dialog is opened

### ISSUE THREAD

**Issue by ajay-jindal** [ariakit/ariakit#1085]
### Current behavior

When accessing any dialog on safari browser in iPhone, background body scroll is triggered when trying to scroll inside the dialog.
Attached video:
https://user-images.githubusercontent.com/93543386/157061840-ccc9a759-895d-48d1-b4fe-f2c0c6e4363b.mp4
Device details: iPhone 12 Pro, iOS 15.3.1

### Steps to reproduce the bug

1. Open ariakit example: https://ariakit.org/examples/dialog on iPhone safari browser
2. open dialog
3. try to scroll outside the dialog using touch. [refer to attached video above]

### Expected behavior

body tag should get overflow: hidden and should not scroll when dialog is open.

### Possible solutions

Using the remote devtool debug from macbook safari for iphone safari i see the body tag is not getting ```overflow: hidden``` like it does in all other chromium browsers and even desktop safari.
probably some code being skipped on iPhone safari.

**Comment by ajay-jindal** [comment]
Hello @diegohaz, could you have a look at above issue please, as it occurs for reakit v1.x as well which we want to use in production soon.
A custom workaround or hot fix in v1 would be awesome, as we are not ready to upgrade to ariakit yet.

**Comment by diegohaz** [comment]
The `overflow: hidden` trick doesn't work on iOS. Reakit v1 uses [`body-scroll-lock`](https://github.com/willmcpo/body-scroll-lock), which "fixes" the behavior on iOS. But every other iOS release breaks this feature. Because of this inconsistency, we decided not to use BSL on v2 and only rely on the simple `overflow: hidden` approach.

Both on v1 and v2, you can always render `<Dialog preventBodyScroll={false}>` and implement your own logic (or use another scroll lock library that works on iOS).
