### ISSUE TITLE
Dialog "setVisible" gets erroneously called with false when using a MenuItem to change the state

### ISSUE THREAD

**Issue by DaniGuardiola** [ariakit/ariakit#1137]
### Current behavior

Trying to open a controlled Dialog from a MenuItem (`onClick={() => setVisible(true)}`) fails when the Menu is `animated: true`.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/charming-payne-z4ej3y?file=/src/bug-demo.tsx
2. Open the Dialog with the button. It works.
3. Open the menu, and then click the "Open dialog" option. It doesn't work.

### Expected behavior

The Dialog opens correctly.

I have investigated a bit, and this is what I know:

- `setVisible` is being called with `false` after setting the state to true.
- I logged the times during render and when the method gets called and they were a few milliseconds apart, around 50-100ms. This is in coherent with the observed behavior that the Dialog is very briefly visible before hiding again, causing a quick flash.
- It only happens if the menu is configured as animated.
- It doesn't matter if the dialog is animated.

### Possible solutions

I'm not really sure.

**Comment by DaniGuardiola** [comment]
@diegohaz as we discussed, this seems to be caused by `focusOnHover`. You suggested setting `focusOnHover={!visible}` as a workaround.

Would something like that be an actual fix in Ariakit though? I'd be happy to work on a PR to prevent triggering focus when visible is false. Let me know.

**Comment by diegohaz** [comment]
That's not the actual fix. We need to improve the logic that detects mouse movement when the mouse leaves the item.

https://github.com/ariakit/ariakit/blob/d342e06c7726a7e8c00df0e6c41758aa73a3d775/packages/ariakit/src/composite/composite-hover.ts#L74

That is, we only want to proceed with the mouse leave event (and focus on the container element) when the mouse leave event is triggered by a mouse movement. For example, if the mouse leaves the item because of a scroll, without mouse movement, it should be ignored.

Right now, clicking on an item that opens a modal (with a backdrop element) will trigger the mouse leave event on the item (because the mouse is leaving the item and entering the backdrop element). This will trigger focus on the menu container element, which will immediately close the modal (because it's an interaction outside the modal).

**Comment by DaniGuardiola** [comment]
Just played with it and it seems like this would fix it:

```ts
addGlobalEventListener("mousedown", resetMouseMoving, true);
```

Let me know if that works, I'm not sure if I'm missing some side-effect here. If you confirm, I'll file a PR.

**Comment by diegohaz** [comment]
Yeah! That's similar to what I thought. I just didn't have the time to test it properly. For example, what happens if you move the mouse just a little after mouse down and before the mouse up or click evens fire?

Anyway, feel free to submit a PR. 😊

**Comment by DaniGuardiola** [comment]
Ah, you're right! I'm thinking then that it probably should be `mouseup` instead, since that's what would precede mouseleave without leaving room for the edge case you mention. I'll put together a PR soon.
