### ISSUE TITLE
Potential performance impact of using Composite and CompositeItem

### ISSUE THREAD

**Issue by youknowriad** [ariakit/ariakit#1301]
In Gutenberg, we rely on Composite and CompositeItem to render a list of "patterns". It's pretty similar to the example in the documentation:

```js
import React from "react";
import { useCompositeState, Composite, CompositeItem } from "reakit/Composite";

function MyPattern( { pattern, composite } ) {
  return (
    <CompositeItem {...composite}><Pattern pattern={pattern} /></CompositeItem>
  );
}

function MyPatternsList( { patterns } ) {
  const composite = useCompositeState();
  return (
    <Composite {...composite} role="toolbar" aria-label="My toolbar">
      {patterns.map( pattern => <MyPattern pattern={pattern} composite={composite} /> )}
    </Composite>
  );
}
```

But since the list of patterns grows overtime (we actually render them one by one lazily to avoid blocking the UI), so we do something like:

```js
function MyLazyPatternList( { patterns } ) {
  const renderedPatterns = useLazyList( patterns );
  return (
    <MyPatternsList patterns={ renderedPatterns } />
  );
}
```

And we wanted to memoize each pattern component to avoid rerendering that component each time a new pattern is added to the list. So we wrap it like so:

```js
const MyPattern = memo( ( { pattern, composite } ) => {
  return (
    <CompositeItem {...composite}><Pattern pattern={pattern} /></CompositeItem>
  );
} )
```

You may have guessed already but this memoization doesn't really work because the "composite" prop seems to be changing every-time a new item is added to the list.

 - Do you have any suggestions how to handle this?
 - Is there something reakit/ariakit can do to help in these situations?

**Note**

The `Pattern` (inner item of `MyPattern`) is already memoized but it's not enough for us, I wanted to move the moization up one level (the root element element of the "map" children )

**Comment by diegohaz** [comment]
Hey @youknowriad!

[v2 will fix a lot of performance issues related to composite components in v1](https://twitter.com/diegohaz/status/1307299869200191490). I don't think it's ready for Gutenberg yet (mostly because the API is not fully consolidated, and there will be breaking changes until the official stable release), but I'd give it a try just to see if the problem is mitigated so you can decide if it's worth investing time on it now or waiting for v2.

In v2, you don't need to pass the `composite` state to `CompositeItem`. So you'll be able to memoize the `MyPattern` component. The `CompositeItem` itself will still re-render because it depends on the `composite.items` state, but it will be consumed in a more performant way through the context (as long as you're not using SlotFill on the patterns).

Here's an example: https://codesandbox.io/s/ariakit-composite-with-async-list-uqpokw?file=/src/App.js

**Comment by youknowriad** [comment]
Thanks for the quick answer Diego.

> . The CompositeItem itself will still re-render because it depends on the composite.items state

This is interesting, Do we need the "composite.items" in the React Tree or only in callbacks. My probably naive guess is that it's mostly useful in callbacks in which case I wonder if `composite.items` could be changed to `composite.getItems: () => []` or `composite.countItems: () => number` in order to avoid the re-rendering entirely.

**Comment by diegohaz** [comment]
> Thanks for the quick answer Diego.
> 
> > . The CompositeItem itself will still re-render because it depends on the composite.items state
> 
> This is interesting, Do we need the "composite.items" in the React Tree or only in callbacks. My probably naive guess is that it's mostly useful in callbacks in which case I wonder if `composite.items` could be changed to `composite.getItems: () => []` or `composite.countItems: () => number` in order to avoid the re-rendering entirely.

There are other components that need `composite.items` in the render phase, so I don't think we can replace this property entirely, but I think it's possible that we change `CompositeItem` so it only depends on a stable `getItems` function created with [`useEventCallback`](https://github.com/ariakit/ariakit/blob/8f24b3804b7f1ebd63be55e02e5bb357371798e1/packages/ariakit-utils/src/hooks.ts#L88-L110).

But I'd like to see if this is really a problem. We're also working on virtualized composite lists, which would probably solve your problem without even the need for the lazy list hook.
