### ISSUE TITLE
Dialog's `hideOnInteractOutside` should exclude backdrop.

### ISSUE THREAD

**Issue by latin-1** [ariakit/ariakit#1349]
### Current behavior

Dialog dismissed on mouse down, but not on click. Non-primary button also dismisses the dialog.

### Steps to reproduce the bug

1. Open https://ariakit.org/examples/dialog
2. Open dialog
3. Right click or middle click on the backdrop

### Expected behavior

- Mouse down on the backdrop should not close the dialog, especially for right-click.

### Possible solutions

Exclude backdrop element from `hideOnInteractOutside`'s behavior.

**Comment by diegohaz** [comment]
After tinkering for a while, I'm not sure this should be the default behavior. For example, this would impact how [context menus](https://ariakit.org/examples/menu-context-menu) work. Do you have any specific use case that's not working because of this?

But this should be able to achieve in userland, which is not the case right now (at least, not in an easy way).

With #1378, which will be released next Monday, you will be able to do this:

```jsx
const ref = useRef(null);
<Dialog
  state={dialog}
  backdropProps={{ ref }}
  hideOnInteractOutside={(event) => {
    return event.type === "click" || event.target !== ref.current;
  }}
>
```
