### ISSUE TITLE
initialFocusRef is not working on click event

### ISSUE THREAD

**Issue by georgekaran** [ariakit/ariakit#1384]
### Current behavior

When assigning a ref to `initialFocusRef` on the `Dialog` and clicking to open, the element is not being focused.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/lively-platform-h5hpc2?file=/src/dialog.tsx
2. Click on the Disclosure.
3. The `Bar` button is not gonna be focused.
4. But when using the keyboard is working as expected.

### Expected behavior

Both clicking and keyboard navigation should correctly focus on `initialFocusRef`

### Possible solutions

By playing around a bit, when I removed the condition `(!target.hasAttribute("data-focus-visible"))` from `onGlobalMouseDown` on `focusable.ts` file it seems to work, but I'm not sure if it's the right solution.

**Comment by diegohaz** [comment]
I can't reproduce it. Do you mean the button doesn't get focused, or just the focus ring that is not visible? If that's the latter, that's expected because the button focus styles use [`focus-visible`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) and our own `data-focus-visible` attribute.

If you want the focus ring to always appear, just use `:focus` instead.

**Comment by georgekaran** [comment]
I've made a video of what's happening, you can see that when I use keyboard navigation, the `initialFocusRef` works as expected, which means that the `Bar` button receives the focus when the `Dialog` is shown. However, when using the mouse click the `Bar` button is not being focused.

https://www.loom.com/share/139eeb46a15a4dfc81c707eb7ce740e3

**Comment by georgekaran** [comment]
🤦🏻‍♂️ You're right, my bad for not testing the `space` key, as I was not seeing the `ring` I assume it wasn't working as expected. Thanks for taking the time to explain.
