### ISSUE TITLE
Combobox with matching item selected

### ISSUE THREAD

**Issue by marcospassos** [ariakit/ariakit#1475]
### Description

An example showing how to keep the matching item selected would be helpful.

### Requirements

- Type a value that matches one o the available items
- Show the matching item as selected until the value no longer matches

**Comment by diegohaz** [comment]
@marcospassos Just to make sure I understood. Is this working as you expect? https://codesandbox.io/s/ariakit-combobox-always-selected-s11kfu?file=/src/combobox-matches.tsx

**Comment by marcospassos** [comment]
Yep. Any chances of including it as part of the API? Don't seem like a specific use case since partial matches are selected, but full matches aren't.

Side question: sometimes, you put part of the imperative logic on the component body instead of in `useEffect` hook. In which case is it recommended?

**Comment by diegohaz** [comment]
> Don't seem like a specific use case since partial matches are selected, but full matches aren't.

By default, when `autoSelect` is used, the first item will be automatically selected only when you *insert text* into the input. This is true for partial *and* full matches:

![Using a combobox with autoSelect behavior](https://user-images.githubusercontent.com/3068563/178777685-c05704f0-531e-406f-a38b-59b42b779daf.gif)

That's also what happens in the video you shared. The auto selection works in the partial match because you open the combobox popover by *inserting text* into the input.

We'll probably add an `autoSelect="always"` prop or something at some point.

> Side question: sometimes, you put part of the imperative logic on the component body instead of in `useEffect` hook. In which case is it recommended?

That's the equivalent of [`getDerivedStateFromProps` for function components](https://reactjs.org/docs/hooks-faq.html#how-do-i-implement-getderivedstatefromprops). It's also mentioned in the [new docs](https://beta.reactjs.org/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes).

Basically, if your effect is only synchronizing state based on props or another state, and the state is defined (that is, `useState` is used) in the *same* component, it's better to do it in the render phase rather than in an effect.

This may be trickier with Ariakit because you don't explicitly see the `useState` calls. We must have a section about that in the docs. But, in short, it's safe to use any `state.setSomething` function during render as long as you're not overwriting it:

```jsx
const combobox1 = useComboboxState();

// ✅ May call combobox1.setActiveId during render

const combobox2 = useComboboxState({
  setActiveId: (activeId) => {
    // custom logic
  }
});

// ❌ Can't call combobox2.setActiveId during render


const combobox3 = useComboboxState({
  setActiveId: props.setActiveId
});

// ❌ Can't call combobox3.setActiveId during render
```

But if you're not sure about what you're doing, it's probably better to use `useEffect` or `useLayoutEffect` there.

**Comment by marcospassos** [comment]
Oh, I see! Thanks for explaining!

**Comment by diegohaz** [comment]
Hey @marcospassos!

The current behavior of `autoSelect` is to focus on the first item only when the user inserts text into the combobox input, which means deleting text and inserting text from paste are ignored.

After researching and receiving more feedback, I'm thinking about changing this behavior so it always auto-selects the first item on change, no matter the input type, similar to what you expected here. The current behavior could be exposed as `autoSelect="insertText"`, but I'd rather have only the default behavior for now.

I have a few questions:
- Would this new behavior still make more sense to you?
- Are you using the current `autoSelect` behavior anywhere? If so, would your component feel broken if this behavior changed?

**Comment by marcospassos** [comment]
Hi @diegohaz!

> * Would this new behavior still make more sense to you?
Yes, in fact, that's the behavior we expected at first.

> * Are you using the current `autoSelect` behavior anywhere? If so, would your component feel broken if this behavior changed?
We're not.
