### ISSUE TITLE
Refs are not assigned inside portals

### ISSUE THREAD

**Issue by marcospassos** [ariakit/ariakit#1511]
### Current behavior

The children of `<Portal/>` don't get ref assigned on the first render. This affects all modals, combobox, selectbox or any order Ariakit's component with `portal={true}`.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/gallant-silence-bu8jx0?file=/src/combobox.tsx
2. Open the console
3. You should see `null`

### Expected behavior

Assign the reference to the div element.

### Workaround

https://github.com/ariakit/ariakit/issues/1511#issuecomment-1157224430

**Comment by diegohaz** [comment]
Unfortunately, that happens to all Portal implementations that work with server hydration. Other libraries will have the same behavior.

Portal will wait for hydration before calling `ReactDOM.createPortal`. Because React doesn't rerender parent components on children's updates, the `Example` component won't rerender. The `ref` gets assigned, but only in a posterior render cycle where `Example` doesn't participate.

That said, the solution is to rerender your component whenever `Portal` rerenders:

```jsx
const [, rerender] = useReducer(() => [], []);
const ref = useRef(null);

<Portal portalRef={rerender}>
  <div ref={ref}>Hello</div>
</Portal>
```

**Comment by marcospassos** [comment]
After a few tries, It seems that the best workaround for such cases is using a ref callback:

```ts
const [element, setElement] = useState<HTMLElement|null>(null);

<Portal>
    <Children ref={setElement} />
</Portal>
```

**Comment by marcospassos** [comment]
In my case, I'm using this to pass a ref to the list box from a hook that handles server-side loading and pagination. So, everything related to the ref is done in a use effect (such as registering scroll listeners).

I'm closing this as there is an acceptable workaround for the use case that originated the issue.
