### ISSUE TITLE
Select - Cannot set defaultVisible to two Select components simultaneously

### ISSUE THREAD

**Issue by binhxn** [ariakit/ariakit#1575]
### Current behavior

Hello!

I have a scenario where I'd like two popovers to be visible by default, at the same time. When I set `defaultVisible` to **true** in both `useSelectState` hooks, only the second Select will display the popover. 

### Steps to reproduce the bug

1. [CodeSandbox](https://codesandbox.io/s/ariakit-select-defaultvisible-issue-fhc8mo?file=/src/App.tsx)
2. Set `defaultVisible` is set to `true` in both `FavoriteFruitOne.tsx` and `FavoriteFruitTwo.tsx`
3. In the UI preview, notice only the popover from `FavoriteFruitTwo.tsx` is displayed

### Expected behavior

When having multiple Select components with `defaultVisible` set to **true** in `useSelectState` hook, all popovers should be visible by default.

### Workaround

https://github.com/ariakit/ariakit/issues/1575#issuecomment-1172946709

**Comment by diegohaz** [comment]
Hey @binhxn! Could you share more details about your specific use case? Screenshots/videos will help a lot.

The behavior you see is expected. It's possible to keep both popovers open, but the exact solution may be different depending on the use case.

**Comment by binhxn** [comment]
Hey @diegohaz !

In Storybook, I use Chromatic to take visual snapshots of components. In the video below, I have **Select** and **MultiSelect** examples with `defaultVisible` to true:

https://user-images.githubusercontent.com/8155387/177011349-85a8dffb-8c48-4e60-bf4b-66929bdf6702.mp4

Having components displayed and grouped together would be very convenient because it saves snapshots and is great for side-by-side visual comparison. However, it's not a big deal to separate them out into their own stories. But because I didn't know that was the expected behavior, I _assumed_ this behavior be a bug.

**Comment by diegohaz** [comment]
When the select popover opens, it gets automatically focused. When the focus moves outside it, it gets closed. You only see the last popover open because the others were closed when the focus shifted to the following popover.

You can keep them open by playing with the `autoFocusOnShow` or `hideOnInteractOutside` props. Since that's Storybook, I'm not sure what's the best approach. I guess I'd keep them in separate stories. But these are the options:

Popover won't automatically move focus when shown:
```jsx
<SelectPopover autoFocusOnShow={false} />
```

Popover won't automatically move focus when *initially* visible ([`useUpdateEffect`](https://github.com/ariakit/ariakit/blob/135d4609e76efe16e65adb41b7cf9edcbb8b2491/packages/ariakit-utils/src/hooks.ts#L206-L225)):
```jsx
const [autoFocusOnShow, setAutoFocusOnShow] = useState(false);

useUpdateEffect(() => {
  setAutoFocusOnShow(true);
}, [select.visible]);

<SelectPopover autoFocusOnShow={autoFocusOnShow} />
```

Popover won't close when interacting (which includes focus) outside:
```jsx
<SelectPopover hideOnInteractOutside={false} />
```

Popover won't close when focusing outside:
```jsx
<SelectPopover hideOnInteractOutside={(event) => event.type !== "focus"} />
```

Popover won't close when interacting with another popover (with the `data-my-popover` attribute):
```jsx
<SelectPopover
  data-my-popover
  hideOnInteractOutside={(event) => !event.target.closest("[data-my-popover]")}
/>
```

**Comment by binhxn** [comment]
That makes a lot of sense. Thank you for the explanation and different solutions, this was very helpful!
