### ISSUE TITLE
Using custom component for radio doesn't change selection when using arrows

### ISSUE THREAD

**Issue by Dremora** [ariakit/ariakit#1761]
### Current behavior

_version: 2.0.0-next.38_

When radio is used with custom element (either `<Radio>` component with `as` property, or `useRadio` hook), using up/down or left/right keys to change the focused element doesn't also update the selected item.
The expected behaviour is the behaviour of the native radio button. It is also described in the [radio group pattern](https://www.w3.org/WAI/ARIA/apg/patterns/radiobutton/).

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/pedantic-grass-6he6gk?file=/src/radio.tsx
2. Click on "apple"
3. Press down button

### Expected behavior

"orange" should become selected (like it does in the [official example](https://ariakit.org/examples/radio)).

**Comment by diegohaz** [comment]
That's expected. If you check the WAI-ARIA pattern, you'll see that the behavior should be different when the radio group is contained in a toolbar. The same applies to other composite widgets that use arrow keys to navigate through items, like menus.

Ariakit assumes that scenario if you're not rendering native radio buttons. In the CodeSandbox you shared, you should be rendering native radio buttons. If you need more customization, you can use the `VisuallyHidden` technique as demonstrated with the Checkbox component on the [Custom Checkbox](https://ariakit.org/examples/checkbox-custom) example.

Let me know if you have a more specific use case that really can't be a native radio button. Otherwise, using the native element is the best solution.

**Comment by Dremora** [comment]
I see, I guess this will be documented once docs are out.

I'm curious, what is the reason for this assumption? Are there any downsides to using non-native checkbox outside of the toolbar? And what if I want to use native checkbox inside the toolbar?
