### ISSUE TITLE
SelectPopover causes console.error when testing with Jest

### ISSUE THREAD

**Issue by georgekaran** [ariakit/ariakit#1800]
### Current behavior

Trying to run tests using the Jest, I'm getting the following error:
![image](https://user-images.githubusercontent.com/23644327/186706279-caf446ed-d5b3-4c85-8ace-eda517b25599.png)

To isolate the problem I used one of the examples on the Ariakit website and got the same result.

### Steps to reproduce the bug

I wasn't able to make it work on the `Codesandbox`, but I will leave the code here.

### `App.tsx`
```tsx
import './styles.css';
import {Combobox, ComboboxItem, ComboboxList, useComboboxState} from 'ariakit/combobox';
import {Select, SelectItem, SelectLabel, SelectPopover, useSelectState} from 'ariakit/select';
import {useRef} from 'react';

const list = [
    'Apple',
    'Bacon',
    'Banana',
    'Broccoli',
    'Burger',
    'Cake',
    'Candy',
    'Carrot',
    'Cherry',
    'Chocolate',
    'Cookie',
    'Cucumber',
    'Donut',
    'Fish',
    'Fries',
    'Grape',
    'Green apple',
    'Hot dog',
    'Ice cream',
    'Kiwi',
    'Lemon',
    'Lollipop',
    'Onion',
    'Orange',
    'Pasta',
    'Pineapple',
    'Pizza',
    'Potato',
    'Salad',
    'Sandwich',
    'Steak',
    'Strawberry',
    'Tomato',
    'Watermelon',
];

export default function Example() {
    const anchorRef = useRef<HTMLButtonElement>(null);

    const combobox = useComboboxState({
        list: list,
        gutter: 4,
        sameWidth: true,
        animated: true,
        focusLoop: false,
        defaultValue: 'Steak',
        getAnchorRect: () => {
            const anchor = anchorRef?.current ?? null;

            if (anchor !== null) {
                return anchor.getBoundingClientRect();
            }

            return null;
        },
    });
    // value and setValue shouldn't be passed to the select state because the
    // select value and the combobox value are different things.
    const {value, setValue, ...selectProps} = combobox;
    const select = useSelectState({
        ...selectProps,
        animated: true,
        focusLoop: false,
        defaultValue: 'Steak',
    });

    // Resets combobox value when popover is collapsed
    if (!select.mounted && combobox.value) {
        combobox.setValue('');
    }

    return (
        <div className="wrapper">
            <SelectLabel state={select}>Favorite fruit</SelectLabel>
            <Select ref={anchorRef} state={select} className="select" />
            <SelectPopover
                state={select}
                composite={false}
                className="popover"
                typeahead
                focusOnMove={false}
            >
                <div className="combobox-wrapper">
                    <Combobox
                        state={combobox}
                        autoSelect
                        placeholder="Search..."
                        className="combobox"
                    />
                </div>
                <ComboboxList state={combobox}>
                    {combobox.matches.map(
                        (value, i) => (
                            <ComboboxItem key={value + i} focusOnHover className="select-item">
                                {props => <SelectItem {...props} value={value} />}
                            </ComboboxItem>
                        ),
                    )}
                </ComboboxList>
            </SelectPopover>
        </div>
    );
}
```

### `App.test.tsx`
```tsx
import {render, screen, waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import Example from './App';

describe('select-combobox', () => {
    it('should filter the options', async () => {
        render(<Example />);

        await userEvent.click(screen.getByRole('combobox'));

        await waitFor(() => {
            expect(screen.getByRole('dialog')).toBeVisible();
        });

        await userEvent.type(screen.getByPlaceholderText('Search...'), 'ca');

        await waitFor(() => {
            expect(
                screen.queryByRole('option', {name: 'Apple'}),
            ).not.toBeInTheDocument();
        });

        expect(screen.getByRole('option', {name: 'Cake'})).toBeVisible();

        expect(screen.getByRole('option', {name: 'Candy'})).toBeVisible();

        expect(screen.getByRole('option', {name: 'Carrot'})).toBeVisible();
    });
});
```

### Expected behavior

I should be able to test the Select component without getting a `console.error`.

**Comment by diegohaz** [comment]
We have a lot of logic happening asynchronously on Popover and other components. They use `queueMicrotask`, `requestAnimationFrame` or (more rarely) `setTimeout`. These are necessary to make things work correctly.

If you're using JSDOM, you can [`waitFor` specific changes in the DOM triggered by those effects](https://javascript.plainenglish.io/you-probably-dont-need-act-in-your-react-tests-2a0bcd2ad65c), but not all of them change the DOM. Even when they do, the change is not always obvious, and most of the time it's not related to your test. You can also [include those timers in your test and wrap them with `act`](https://twitter.com/diegohaz/status/1560525455383461888). In both cases, your tests may break due to a new version of Ariakit introducing new async actions.

Instead, I'd suggest using something like Playwright or Cypress to test your components. There are a lot of things in the browser that JSDOM can't reproduce. In a robust application, you'll need to test things in a real browser anyway.

Internally, we do use JSDOM for most tests (and Playwright for some others), but we have functions like `click`, `hover`, etc. that simulate real user interactions, including the timers that browsers flush automatically. All these timers are wrapped with `act`, so we don't have those issues in our tests. You can raise an issue on the `@testing-library/user-event` repo to include those timers there as well.

Here's an example:
https://github.com/ariakit/ariakit/blob/1df3eae9f87373618b1a2145f07a44a52c0c8c0e/packages/ariakit-test/src/press.ts#L213-L239

**Comment by georgekaran** [comment]
Thanks for such a detailed explanation.

I've tried to apply the same pattern in the select tests and it didn't work 😞 (Still getting the act error).

```tsx
it('should filter the options', async () => {
    render(<Example />);

    await userEvent.click(screen.getByRole('combobox'));

    await flushMicrotasks();

    await sleep(100);

    await waitFor(() => {
        expect(screen.getByRole('dialog')).toBeVisible();
    });

    await userEvent.type(screen.getByPlaceholderText('Search...'), 'ca');

    await flushMicrotasks();

    await sleep(100);

    await waitFor(() => {
        expect(
            screen.queryByRole('option', {name: 'Apple'}),
        ).not.toBeInTheDocument();
    });

    expect(screen.getByRole('option', {name: 'Cake'})).toBeVisible();

    expect(screen.getByRole('option', {name: 'Candy'})).toBeVisible();

    expect(screen.getByRole('option', {name: 'Carrot'})).toBeVisible();
});
```

Is there any other workaround that we could try? Although we in fact have plans to use Cypress in our library, it will not happen within the next weeks, and, using Jest is the only way for us right now.

**Comment by diegohaz** [comment]
You can try to use `ariakit-test` (instead of `@testing-library/user-event`). But I don't have plans to make this package stable any time soon. There will be breaking changes in patch and minor versions.
