### ISSUE TITLE
Value for hidden native select is not set if there are no select items

### ISSUE THREAD

**Issue by Jackardios** [ariakit/ariakit#1989]
### Current behavior

I want to make a select that lazily loads items only when it's open. When the initial value of the required select is set, but the items of the select have not yet been loaded, when trying to submit the form, it writes the error "Please select one of the items." I'm assuming the reason is that the initial value is not set to the hidden select if the element doesn't already exist. I also assume that this behavior may be intentional, but how then to implement lazy loading of items?

https://user-images.githubusercontent.com/24757335/197332547-5027ca89-bb3b-4f7d-a436-7c324d481d92.mov

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/funny-chaplygin-eue0nh?file=/src/select.tsx
2. Click submit button
3. Form not submitting with error "Please select one of the items"
4. Open select
5. Wait for items to load
6. Click submit button
7. Form submits as expected

### Expected behavior

If the value of the required select is set but the items of that select have not yet been loaded, the form should submit

### Workaround

https://github.com/ariakit/ariakit/issues/1989#issuecomment-1287725587

### Possible solutions

https://github.com/ariakit/ariakit/issues/1989#issuecomment-1287725587

**Comment by diegohaz** [comment]
The problem is that a native `<select>` without any `<option>` will have no value, even if you set the `value` or `defaultValue` props, which are special React props.

In HTML, `<select>` doesn't have a `value` attribute. The value is set by setting the `selected` attribute on the selected option. That is, we need to render an option to have it selected.

As a workaround, you can render a `<SelectItem hidden value={select.value} />` element when there's no items.

However, the library may also automatically render an option with the current value if there are no other options.

**Comment by Jackardios** [comment]
@diegohaz Got it, thanks a lot for the workaround!
