### ISSUE TITLE
hideOnHoverOutside can't override by function in useMenu

### ISSUE THREAD

**Issue by 0xDing** [ariakit/ariakit#2053]
> Here's a workaround:
> 
> ```js
> const hovercard = useHovercardState();
> 
> <Hovercard
>   hideOnHoverOutside={() => {
>     // Overwrite the default behavior
>     setTimeout(hovercard.hide, 500);
>     return false;
>   }}
> >
> ```

but this not work with `useMenu` and `Menu` component's hideOnHoverOutside attribute

_Originally posted by @0xDing in https://github.com/ariakit/ariakit/issues/1662#issuecomment-1316109455_

**Comment by diegohaz** [comment]
Hi @0xDing! Could you please provide a CodeSandbox with a reproduction of what you're trying to do?

**Comment by 0xDing** [comment]
https://codesandbox.io/s/hungry-visvesvaraya-8dhj15

I expect to override the default behaviour of hideOnHoverOutside to close the menu in any case whenever the mouse moves outside the button or menu.

But once the mouse has passed over the menu, the menu needs to be clicked outside to be closed.

It seems to be that useMenu is executed earlier when the value of hideOnHoverOutside is a function. Therefore it is not possible to override the behavior of hideOnHoverOutside in useHovercardState with this solution.


Thanks

**Comment by diegohaz** [comment]
@0xDing That's expected. When you hover over a menu item, it gets focused because its `focusOnHover` prop is `true` by default. 

`hideOnHoverOutside` is ignored when the hovercard has focus:

https://github.com/ariakit/ariakit/blob/1937330ffc4db2b11c2007f3983a77ae97fa2a90/packages/ariakit/src/hovercard/hovercard.tsx#L45-L46

You can set `focusOnHover={false}` to the `MenuItem`s or write a custom logic to hide the menu.
