### ISSUE TITLE
Tooltip accessibility: `aria-labeledby` vs `aria-describedby`

### ISSUE THREAD

**Issue by brookewp** [ariakit/ariakit#2228]
### Current behavior

Hi there! 👋  

Although the current behaviour is intentional, I've marked this as a potential bug; by default, the Tooltip component is not entirely accessible to screen readers. 

Currently, Tooltip uses `aria-labeledby` instead of `aria-describedby` but has the option to change that with `described`:

https://github.com/ariakit/ariakit/blob/5d8a1f047fcadcf117073c70359663a3946b73bf/packages/ariakit/src/tooltip/tooltip-anchor.ts#L122-L136

### Steps to reproduce the bug

1. Visit the Tooltip documentation/example: https://ariakit.org/components/tooltip
2. Enable a screen reader 
3. Tab to the Tooltip anchor
4. Hear that only the Tooltip text is announced 

#### Screenshot of all that VoiceOver reads:

<img width="813" alt="Screenshot 2023-03-24 at 9 49 15 AM" src="https://user-images.githubusercontent.com/35543432/227592406-d8204ee6-461c-4f53-ae1d-2e73652647d8.png">

### Expected behavior

From the guidelines in [WAI-ARIA Tooltip Pattern](https://ariakit.org/components/tooltip), it states:

> The element that triggers the tooltip references the tooltip element with [aria-describedby](https://w3c.github.io/aria/#aria-describedby).

Since this isn't enabled by default, the anchor element is not announced, only the tooltip. Of course, with `described={ true }` we get the expected behaviour: 

![example](https://user-images.githubusercontent.com/35543432/227592997-feaefc75-b56f-46b2-be30-1532ea460c67.gif)

A sandbox with a `described` example demonstrated in the gif above: 
https://codesandbox.io/embed/tooltip-with-described-8dzfew?fontsize=14&hidenavigation=1&theme=dark

---

#### The question:  
<br>
Why is <code>aria-labelledby</code> the default instead of <code>aria-describedby</code> ? Is there a scenario where a developer might want to use <code>aria-labelledby</code>  instead?

**Comment by diegohaz** [comment]
Hi @brookewp! Thank you for bringing this up.

After analyzing how sites were using tooltips, we've introduced `aria-labelledby` on Tooltip in v2 because, in most cases, the tooltip was being used as a label (for example, for buttons with an icon and no visible label). Even though that's not mentioned in the ARIA docs, screen readers, in general, would provide more consistent and meaningful announcements with `aria-labelledby` in those scenarios.

Consider, for example, a button with an unlabelled (or `aria-hidden`) `<svg>` and a tooltip with the text `Undo`. We can talk about the correctness of this example, but this is a widespread use case. The tooltip is clearly being used as a label in this case. For a non-sighted screen reader user, though, the tooltip doesn't exist. They can only perceive a label or description.

In that case, if `aria-describedby` was used, the button would have no accessible name. Most combinations of browsers and screen readers would announce something like `button, Undo`. On VoiceOver, it would be `Undo, button, Undo`. If the button already has `Undo` as its accessible name (let's say the `<svg>` is labeled), VoiceOver would still announce `Undo, button, Undo`. In contrast, some other screen readers, like NVDA, would be smart enough to announce only the label: `Undo, button`.

On the other hand, if we use `aria-labelledby` to reference the tooltip, it will always be `Undo, button`.

But it's definitely a bug in our tooltip example. We should either use an icon button representing most use cases on existing web apps or use the `described` prop. Or we can keep `aria-describedby` the default, like in v1, and add a `labelled` prop or something.

**Comment by brookewp** [comment]
Thank you for the detailed explanation! 
>But it's definitely a bug in our tooltip example. We should either use an icon button representing most use cases on existing web apps or use the described prop. Or we can keep aria-describedby the default, like in v1, and add a labelled prop or something, that would also remove the role="tooltip" attribute.

All of these options would help to clarify but I am partial to the last suggestion; because of ARIA documentation, I would assume that `aria-describedby` would be the default. But now I understand why `aria-labeledby` is also an option. 🙂

**Comment by diegohaz** [comment]
So here's my idea:

1. We add a `type` option to `useTooltipState`/`useTooltipStore` (see #1875). Accepted values are `"label"` and `"description"`.
2. The `type` will be automatically inferred based on whether the tooltip anchor already has an accessible name. So in most cases, it wouldn't need to be set.

**Comment by diegohaz** [comment]
> 2\. The `type` will be automatically inferred based on whether the tooltip anchor already has an accessible name. So in most cases, it wouldn't need to be set.

It turns out that identifying if the element has an accessible name isn't a trivial task. We could use [`dom-accessible-api`](https://www.npmjs.com/package/dom-accessibility-api), which is used by testing-library, but I don't think it's worth it just for this feature.

For now, users will have to explicitly define `type="label"` if the tooltip is intended to be a label.
