### ISSUE TITLE
Cannot use Ariakit in StackBlitz

### ISSUE THREAD

**Issue by IanVS** [ariakit/ariakit#2483]
### Current behavior

I'm trying to reproduce a strange behavior I'm seeing, so I created a stackblitz, but I found that StackBlitz itself will not load up.  I see in the network tab that it is trying to load cjs assets, which is odd because I'm explicitly importing from `@ariakit/react/esm/popover`.  Maybe there's a dual-packaging issue happening?

<img width="616" alt="image" src="https://github.com/ariakit/ariakit/assets/4616705/2ed0b962-94ff-47e0-8d0f-3862635a7b12">

### Steps to reproduce the bug

1. Open sandbox: https://stackblitz-starters-z6xwmz.stackblitz.io
2. Notice the page just spins
3. Check network tab to see failed requests for cjs dependencies

### Expected behavior

I don't think cjs assets should be requested at all, when using ESM.

### Workaround

Use StackBlitz web containers: https://github.com/ariakit/ariakit/issues/2483#issuecomment-1569145622

### Possible solutions

Same as #2400

**Comment by diegohaz** [comment]
The `esm` and `cjs` folders aren't supposed to be used directly. If you're working on an ES module, importing from `@ariakit/react` will automatically import from the `esm` folder. If you're on a CJS module, it will use the `cjs` folder.

The sandbox you provided is a common JS module. You could turn it into ESM by setting `"type": "module"` in the package.json or renaming the file to `.mjs`/`.mts`. But I don't think `react-scripts` supports ESM (see #2400).

Since it's a common JS module, importing directly from the `esm` folder will only work one-level deep in the dependency tree. Transitive dependencies like `@ariakit/react-core` will still resolve to `cjs`.

The problem, though, seems to be related to unpkg (which Stackblitz uses to download dependencies) not automatically resolving the `.cjs` extension as it does with `.js`.

- Resolved to `.js`: https://unpkg.com/@ariakit/react-core@0.2.4/esm/radio/radio
- Can't resolve to `.cjs`: https://unpkg.com/@ariakit/react-core@0.2.4/cjs/radio/radio
- Works: https://unpkg.com/@ariakit/react-core@0.2.4/cjs/radio/radio.cjs

I guess the suggested solution on #2400 may help with this issue too.

---

You can use StackBlitz web containers, though. You can open any example on the site on StackBlitz using the open preview menu:

<img width="435" alt="screenshot of the ariakit site showing the open preview dropdown open" src="https://github.com/ariakit/ariakit/assets/3068563/1b27405e-b3da-48b8-9d48-aab32be172b6">

**Comment by diegohaz** [comment]
It should be working now: https://stackblitz.com/edit/stackblitz-starters-z574kq

Unfortunately, it seems that StackBlitz doesn't automatically include type definitions from transitive dependencies, so I manually installed the `@ariakit/core` and `@ariakit/react-core` packages, but this is not required in a real app.

**Comment by IanVS** [comment]
Oh wow, I guess I assumed that since @patak-dev is at Stackblitz, that the default react starter templates would be ESM and not using create-react-app :-P.    I should have actually checked.

Thanks for improving the experience there nonetheless, @diegohaz!
