### ISSUE TITLE
RFC: Component providers

### ISSUE THREAD

**Issue by DaniGuardiola** [ariakit/ariakit#2658]
### Motivation

Some "components" (as in "units of UX", e.g. a menu) are actually made of different components (as in React/Vue/etc components). For example, to build a menu with Ariakit you need to compose `Menu`, `MenuButton`, `MenuItem`, etc. together.

These components need to share a state, which is what **component stores** are for. For example, to build a menu, you first create a menu store (which holds the state) and pass it to the different components:

```tsx
const menuStore = useMenuStore();
return (
  <>
    <MenuButton store={menuStore} />
    <Menu store={menuStore} />
  </>
);
```

This is a great approach for composability, but sometimes it can be a hassle, for example:

```tsx
const menuStore = useMenuStore();
return (
  <>
    <MenuButton store={menuStore} />
    <Menu store={menuStore}>
      <MenuItem store={menuStore} />
      <MenuItem store={menuStore} />
      <MenuItem store={menuStore} />
      <MenuItem store={menuStore} />
      <MenuItem store={menuStore} />
      <MenuItem store={menuStore} />
      <MenuItem store={menuStore} />
    </Menu>
  </>
);
```

That's one of the reasons why a [hybrid implicit/explicit state](https://github.com/ariakit/ariakit/issues/745) approach was introduced, through the use of React context:

```tsx
const menuStore = useMenuStore();
return (
  <>
    <MenuButton store={menuStore} />
    <Menu store={menuStore}>
      <MenuItem />
      <MenuItem />
      <MenuItem />
      <MenuItem />
      <MenuItem />
      <MenuItem />
      <MenuItem />
    </Menu>
  </>
);
```

This RFC aims to further simplify building these kinds of components, at both the **direct usage** and **abstraction** level. Abstraction, in this context, means creating a custom component (e.g. a design system component for an organization) that wraps Ariakit, as opposed to being directly used for a specific UI.

#### The use case

Some users choose a "single component" approach, due to strict API versioning requirements and similar constrains. For example:

```tsx
function MyMenu(props) {
  const menuStore = useMenuStore();
  return (
    <>
      <MenuButton store={menuStore} />
      <Menu store={menuStore}>
        ...
      </Menu>
    </>
  );
}
```

This is a valid approach, but another common approach is to "re-export" a styled ("skinned") version Ariakit for the most part, with the goal of letting users of the custom component interact with Ariakit, as well as any custom features added on top.

There are advantages to this approach, as it can result in less maintenance work and great flexibility and composability for users. However, since an important goal of design systems is to simplify the most common use cases for app developers, the "wiring" required for component stores can prove complex.

#### Component roots

Inspired by (and improving on) other UI libraries like Radix and Headless UI, the concept of a **root component** can be a good compromise to address this use-case.

The responsibility of a root component is to provide a context (specifically, a React context) for a component store that related components can consume, for example:

```tsx
const menuStore = useMenuStore();
return (
  <MenuRoot store={menuStore}>
    <MenuButton />
    <Menu>
      <MenuItem />
    </Menu>
  </MenuRoot>
);
```

However, it can be taken a step further for much improved flexibility by adding another responsibility to root components: creating a component store if it's not provided.

This allows an API like this:

```tsx
return (
  <MenuRoot>
    <MenuButton />
    <Menu>
      <MenuItem />
    </Menu>
  </MenuRoot>
);
```

There are a lot of cases where having control over the component store is not necessary. For example, in a simple menu, a developer won't usually care about controlling whether the menu is open or closed. This is somewhat (but not exactly) analogous to the concept of "uncontrolled components", in the sense that you don't need to create and pass the state for the component to work as intended.

Going further, the root component can take store creation options. This allows simpler customization, e.g:

```tsx
<MenuRoot placement="top">
  ...
</MenuRoot>
```

And also simpler and finer control of state, e.g:

```tsx
<MenuRoot open={open} setOpen={setOpen}>
  ...
</MenuRoot>
```

#### Breaking changes

Technically, nothing should break. However, there needs to be a minor API change: components that currently require a component store need to make the prop optional, to allow for the new context-based source. This means that the potential error when a store is not provided needs to be moved from "typecheck-time" to execution time.

Other than than, this change should be 100% retro-compatible and users won't be impacted by an upgrade.

#### Conclusion

This change adds on top of the (already awesome, IMHO) API and architecture of Ariakit, adding a very convenient option for users. It unlocks simpler implementations and abstractions, and provides familiarity to users coming from other popular UI libraries like Radix or Tailwind's Headless UI.

And it will make the life of design system developers (such as myself) much easier.

### Usage example

```tsx
return (
  <MenuRoot placement="top">
    <MenuButton />
    <Menu>
      <MenuItem />
    </Menu>
  </MenuRoot>
);
```

### Requirements

- Component roots are implemented. If a store is not provided to them, they create their own store with the provided store props. The store is then passed through React context.
- Components use the store from the context if available (and if a store has not been explicitly passed to them).

### Workaround

Manual wiring: implement your own root component and wrap Ariakit components to get it from the context.

**Comment by diegohaz** [comment]
Hey @DaniGuardiola! Thanks for posting the RFC.

It would be a great addition to the library. Here are some thoughts:

## Naming

I see two issues with the `Root` suffix:

1. "root" sounds like something that should be required, which wouldn't be the case here. If a "root" component exists, rendering a component tree without it doesn't sound right.
2. It's not obvious that the root component won't render any element.

I believe `Provider` may be a better suffix as it's already a known concept in React.

## Single top-level components

Some components like [RadioGroup](https://ariakit.org/components/radio) and [Toolbar](https://ariakit.org/components/toolbar) are already the root components in their modules. Do they need separate `RadioProvider` and `ToolbarProvider` components? For consistency, I believe they do. But maybe they should also accept the provider's props and render the provider themselves.

At the same time, I don't think [Composite](https://ariakit.org/components/composite), used by `RadioGroup` and `Toolbar`, should follow the same pattern. `Composite` is also used by [Combobox](https://ariakit.org/components/combobox), which is not the single root component of the module. It would be weird to accept store props on it.

We will need to decide on each component individually.

## Passing the `store` prop together with store props

Consider the following code:

```jsx
<MenuProvider open={open} setOpen={setOpen}>
```

Let's say months later, I need to access the menu store to implement something else. If the provider supports *either* the `store` or the store props, I'd have to change it to something like this:

```jsx
const store = useMenuStore({ open, setOpen });

<MenuProvider store={store}>
```

But, as a user, I'd like to change my code as little as possible by doing something like this instead:

```jsx
const store = useMenuStore();

<MenuProvider store={store} open={open} setOpen={setOpen}>
```

Fortunately, this is already supported by the stores. We can pass another `store` as a prop to any component store hook, and the states will be synced:

```js
const store = useMenuStore();
const menu = useMenuStore({ store, open, setOpen });
```

If both stores define `open`, the last one will take precedence. I expect this behavior to be the same with component providers (the props passed to the provider taking precedence), but it may be unclear. I don't know.

## Dynamic `store` prop

With the pattern above, we could simply `useMenuStore(props)` inside the component provider, which would also account for the `store` prop. But, currently, the `store` prop on component store hooks doesn't support dynamic values. Only the initial `store` prop passed in the initial render will work.

I believe that can be supported, but will require more work.

## Combining components with their stores

Some combinations like [Select with Combobox](https://ariakit.org/examples/select-combobox) require that we pass the combobox store as a prop to the select store. There's a specific `combobox` prop on the select store for this because we can't sync all states (we have to exclude `value`, for example).

How should we approach this? Here's a version that should be always supported anyway:

```jsx
const combobox = useComboboxStore();

<SelectProvider combobox={combobox}>
  <Select />
  <SelectPopover>
    <ComboboxProvider store={combobox}>
      <Combobox />
      <ComboboxList>
        <ComboboxItem render={<SelectItem />} />
```

But maybe there's a way to support this without having to explicitly instantiate the combobox store?

```jsx
<ComboboxProvider>
  <SelectProvider> {/* reads the combobox context to set its combobox prop */}
    <Select />
    <SelectPopover>
      <Combobox />
      <ComboboxList>
        <ComboboxItem render={<SelectItem />} />
```

## `mounted` state

The `mounted` state is commonly used to dynamically render disclosure content components. Unless we add a `setMounted` prop or something, the component store hook will have to be used to access this state (`store.useState("mounted")`).

**Comment by DaniGuardiola** [comment]
@diegohaz thanks for your response!

- Naming: completely agree, let's go with `-Provider`.

- Single top-level components:
  - One solution is just keeping it separate. It also favors consistency. It might feel a little weird to have ToolbarProvider > Toolbar but it's clearer and abstractions can still create a single root by composing the two in the same element.
  - For the above solution, there's a problem: if you combine the two, the props are also combined, and you now need to extract the provider props from the rest to properly forward them. Since the props might change across Ariakit versions, maybe Ariakit could expose something like `useToolbarStoreProps` that does this for you with proper types (e.g. using `Pick` and `Omit`).

- Passing the store prop together with store props: feels like a simple and useful API. I think with good documentation this should be fine.

- Dynamic store prop: agreed that this would be nice. Since it requires additional work, I think it's fine to release an initial version that just errors when the store changes, with a clear message. The dynamic part can be added later as a new feature.

- Combining components with their stores: the suggested API seems right to me, as long as it's well documented. The only thing that stands out is that, again, this would require "splitting" the props so that they can be forwarded to their respective components, when combining both providers. I'd suggest a similar solution to the one I shared above.

- mounted state: yep, this feels right to me. I would expect an Ariakit-exported useStoreContext (e.g. useMenuStoreContext) hook so that I can then do store.useState("mounted").

**Comment by DaniGuardiola** [comment]
Something that comes to mind that might be problematic is the fact that components can now receive a store through context and as a prop. I'm curious how this is handled in components such as `MenuItem` where this already happens.

Thinking in terms of an abstraction, e.g. `MyMenu`, with this RFC you'd be able to do something like this:

```tsx
function MyMenu(props) {
  const store = Ariakit.useMenuStoreContext();
  const mounted = store.useState("mounted");
  return mounted ?<Ariakit.Menu {...props} /> : null;
}
```

However, this doesn't seem right, because `props.store` might be set. In that case, you'd think to do something like this to fix it:

```tsx
function MyMenu(props) {
  const store = props.store ?? Ariakit.useMenuStoreContext();
  const mounted = store.useState("mounted");
  return mounted ?<Ariakit.Menu {...props} /> : null;
}
```

But, of course, this is not valid React (conditional hook). The way we handle this in our userland implementation of providers is that we throw an error if `props.store` goes from having a value to not having a value or viceversa.

I guess this is related to the whole dynamic stores thing. Maybe the consumer hook exported from Ariakit could take an argument and handle this for the user?

```tsx
function MyMenu(props) {
  const store = Ariakit.useMenuStoreContext(props.store);
  const mounted = store.useState("mounted");
  return mounted ?<Ariakit.Menu {...props} /> : null;
}
```

**Comment by Saeris** [comment]
So, I've been doing some thinking on Ariakit's composition model specifically around forms and the context provider pattern that `Ariakit.Form` exemplifies.

In general, I like this idea of a component root to negate the need to manually wire up a component state store to multiple compositional elements. There are cases where you want the store in order to layer in additional logic, be it for user interactions or styling, etc, but I think those are an optional case not the norm. A Root element serves as a better model for this norm, where composition of the sub-elements is the thing users care the most about.

In my own use of Ariakit I've fallen into a pattern of taking the primitives it provides, applying styling to them, and then exposing that in my UI library as a component, which for most input elements results in me needing to provide two implementations: what I refer to as capital Inputs and Fields. Let's define some terms:

![image](https://github.com/ariakit/ariakit/assets/3144549/a0ec9e10-786a-4a8f-b8da-193d12a1eede)

An Input is commonly a standalone html input element that follows some WAI-ARIA interaction pattern and is typically used as a "controlled component", meaning you pass it the `value` and `setValue`/`onChange` props. You might use a standalone input for something like a search box or a filter for a list. In these use cases, the application immediately does something with the value as it changes, there typically isn't a submit action by the user in order for the app to act on the value of the input.

A Field on the other hand is always part of a Form. Its state is wired up to the Form's state via a `name` prop and typically has supporting elements such as a Label, Description, and/or an Error message. Validation happens whenever the field's value changes, but a submit action is required for the Field's value to "do" something.

Because a common feature of a Field is the supporting elements, you would naturally want to create an abstraction in your codebase to cut back on repeated compositional code. In another library like Formik or React Hook Form, this might be handled with a `render` prop. If you tried to build out even a simple form without creating a Field abstraction, you'll very quickly repeat a lot of boilerplate code.

You might at this point assume you could use a slot pattern to plug an Input into a component containing these supporting elements, which unfortunately doesn't always work. What might work for a Text or Select input might not work with say, a Switch or a Radio. Here's an example from Discord's settings UI that shows a small variety of Fields, each having their own different styling and compositional hierarchy:

![image](https://github.com/ariakit/ariakit/assets/3144549/5a491427-7f64-4b9a-acfa-642ca40f0c1d)

So that in mind, I think you would naturally need to create one or more bespoke Fields per Input your UI library might have.

Okay, so to tie all this back into the discussion at hand: I would like to see Ariakit's component API model here to better support the above, taking into account that there are multiple compositional layers at play here. Where this issue is brought up in the context of a single component pattern such as a Combobox, I want to draw attention to the fact that a Combobox is unlikely to exist in a void and likely will be used as a compositional element of a larger pater of your app, such as a Form.

What we're discussing here roughly breaks down the same way that `Ariakit.Form` works today, you're creating a compositional boundary and you want to represent that boundary with a Root component, which wires up child elements to a store context. What I would like to see is some thought put into nested compositional boundaries.

A pain point I have right now with all of the form components is that they necessarily have to live as children of an `Ariakit.Form`, meaning that if I want to have a standalone Input with similar supporting elements of a Field, I will need to create a third abstraction, a "standalone Field".

If we can get to a point with the component APIs such that I can write even less boilerplate code to use Inputs in different contexts that would be ideal. It would be ideal if I didn't have to write additional supporting code to wire up a Text input or a Combobox, or a Checkbox group to a parent Form. Nesting any of those within a Form's children should be enough for all of those to be automatically wired into the form's state. If anything, it would be more convenient to break out of this being the default behavior via say a `standalone` prop. Maybe a useful analogy here is to explicitly opt into absolute positioning to break out of a relative layout.

Hope this rambling give you some food for thought! I'm still thinking through the details of this myself, so if you have questions I'll try my best to answer them.

**Comment by Saeris** [comment]
Here's an example sandbox I threw together for some coworkers a while back. It shows the abstractions I made for form fields, and the intent here was to demo that you needed very little in terms of JSX and props to build out a whole form.

https://codesandbox.io/p/sandbox/accessible-form-demo-e83s4q?file=%2Fsrc%2Fpages%2Fcomponents.tsx%3A1%2C1

**Comment by ccschmitz** [comment]
I like this pattern, and it's actually something we've implemented in our component library at [highlight.io](https://highlight.io). Has been a nice improvement to the DX and agree it would make sense to incorporate in Ariakit.

I agree "Provider" makes more sense than "Root" and fits well into the mental model React devs already have.

**Comment by DaniGuardiola** [comment]
:tada: :tada: nice work @diegohaz
