### ISSUE TITLE
Home key does not act as expected on a combobox when followed by a list of items

### ISSUE THREAD

**Issue by nats12** [ariakit/ariakit#2889]
### Current behavior

Given a component of the following structure..

```
...
<label className="label">
    Your favorite fruit
    <Ariakit.Combobox> placeholder="e.g., Apple" className="combobox" />
</label>
<Ariakit.ComboboxPopover ... className="popover">
	<Ariakit.ComboboxItem ... className="combobox-item">
      	🍎 Apple
  	</Ariakit.ComboboxItem>
</Ariakit.ComboboxPopover>
...
```

When typing into the input field and pressing the home key (in Mac's case `fn + ArrowLeft`), the cursor is not placed at the start of the text as is expected. Instead, the first option is highlighted. This is down to the `moveOnKeyPress`. It's set to `true` as a default so that we can cycle through a list of options with the arrow keys.

### Steps to reproduce the bug

1. As seen on the website's [code](https://ariakit.org/components/combobox) itself, see demo [here](https://share.cleanshot.com/FyR6HPfC). Press the home key (for Windows) or `fn+ArrowLeft` (for Mac) whilst the cursor is at the end of the typed input.

### Expected behavior

The Home shortcut should bring the cursor to the start of the inserted text, not highlight the first option in the list.

### Workaround

https://github.com/ariakit/ariakit/issues/2889#issuecomment-1740689039

### Possible solutions

Could we toggle this value depending on the intent at the time of pressing arrow keys? I.e. if the key being pressed is `ArrowDown`, then it makes sense to highlight the first option, otherwise let the Home key act as intended.
 
Something like...

```
function handleMoveOnKeyPress() {
            return eventCode === 'ArrowDown' || eventCode === 'ArrowUp' ? true : false
        }
```

You'd have to tap into the event to detect the key being pressed and passed down (perhaps via `onKeyDown` and setting it to some local state, since `moveOnKeyPress` doesn't sent the event.

**Comment by diegohaz** [comment]
Hi @nats12! Thanks for reporting.

Although the APG is not really a spec, it indicates that [either option is acceptable](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/#:~:text=does%20not%20move.-,Home,to%20the%20combobox%20and%20places%20the%20cursor%20after%20the%20last%20character.,-Any%20printable%20character):

> <kbd>Home</kbd> (Optional): Either moves focus to and selects the first option or, if the combobox is editable, returns focus to the combobox and places the cursor on the first character.
> <kbd>End</kbd> (Optional): Either moves focus to the last option or, if the combobox is editable, returns focus to the combobox and places the cursor after the last character.

However, I've noticed that the current behavior is inconsistent. It only shifts to an item on <kbd>Home</kbd> and <kbd>End</kbd> keystrokes when there's no active item. If we agree that <kbd>Home</kbd> and <kbd>End</kbd> should move items (which is open for discussion), rather than altering the scroll position or the input cursor, like in a native input, we need to standardize this behavior. This way, pressing these keys when an item is already active will also function.

In any case, you can disable this by using the [`moveOnKeyPress`](https://ariakit.org/reference/combobox#moveonkeypress) prop:

```jsx
<Combobox
  moveOnKeyPress={(event) => event.key !== "Home" && event.key !== "End"}
/>
```

**Comment by diegohaz** [comment]
I can no longer reproduce the original issue.
