### ISSUE TITLE
Menu flickering inside shadow dom

### ISSUE THREAD

**Issue by ilyasmez** [ariakit/ariakit#2983]
### Current behavior

The <Menu> component's submenus flicker when used inside shadow dom. Which makes it hard to select a submenu item.

https://github.com/ariakit/ariakit/assets/30146019/64c978af-15d5-49a0-a310-5d102bd84ac1

### Steps to reproduce the bug

1. Open sandbox: https://stackblitz.com/edit/ondrbq?file=app%2Fpage.tsx
2. Open the menu and mouse the cursor over the items with a submenu.

In the example above is the same as the default demo, expect that I've wrapped the menu example in `ShadowRoot.div` to render it inside shadow dom, and (optional) moved the styles inside the shadow dom, so the menu looks presentable.

This is not related to `react-shadow`, this can be reproduced also by manually creating a shadow dom and rendering the menu there.

### Expected behavior

The menu should work without flickering.

### Workaround

https://github.com/ariakit/ariakit/issues/2983#issuecomment-1775092916

### Possible solutions

https://github.com/ariakit/ariakit/issues/2983#issuecomment-1775092916

**Comment by diegohaz** [comment]
The `Menu` component, which uses `Hovercard` at its core, currently doesn't account for shadow roots. 

You can mitigate this issue by implementing a custom [`hideOnHoverOutside`](https://ariakit.org/reference/menu#hideonhoveroutside) logic that reads the event target from `event.composedPath()` rather than `event.target`.

```jsx
<Ariakit.Menu
  // TODO: Remove when https://github.com/ariakit/ariakit/issues/2983 is fixed
  hideOnHoverOutside={(event) => {
    if (!menu.parent) return false;
    const { contentElement, anchorElement } = menu.getState();
    const [target] = event.composedPath() as Node[];
    if (!target) return false;
    const activeElement = target.ownerDocument?.activeElement;
    if (anchorElement?.contains(target)) return false;
    if (contentElement?.contains(target)) return false;
    if (activeElement && target.contains(activeElement)) return false;
    return true;
  }}
>
```

A possible solution within the library involves refining this line:

https://github.com/ariakit/ariakit/blob/6c695e868a4225b584dad634042f5a73d1ca9209/packages/ariakit-react-core/src/hovercard/hovercard.tsx#L171

**Comment by ilyasmez** [comment]
Thank you for quickly providing a workaround @diegohaz , it works perfectly!

I'll see if I can find time and hopefully open a PR with a fix.
