### ISSUE TITLE
[ComboBox] VoiceOver announces an extra "selected" after selecting/deselecting item

### ISSUE THREAD

**Issue by emlai** [ariakit/ariakit#3030]
### Current behavior

For the multi-select combo box example (https://ariakit.org/examples/combobox-multiple), VoiceOver announces "selected, selected" when selecting an item, or "not selected, select" when deselecting an item:

<img width="470" alt="Screenshot 2023-11-08 at 16 52 45" src="https://github.com/ariakit/ariakit/assets/7543552/47fb32d5-6052-4a15-97d6-1d5f1e631bdc">

### Steps to reproduce the bug

1. Go to https://ariakit.org/examples/combobox-multiple
2. Enable VoiceOver
3. Select / deselect menu items via keyboard

### Expected behavior

VoiceOver only announces "selected" or "not selected" once per selection change. 

This works as expected for example for the Downshift.js multi-select combo box: https://www.downshift-js.com/use-combobox#basic-multiple-selection

**Comment by diegohaz** [comment]
I believe VoiceOver is signaling two distinct "selected" states. The first one pertains to the checked state, whereas the latter corresponds to the focus state. Despite the ambiguity, it appears intentional, as it's the outcome of using `aria-multiselectable="true"` on the `role="listbox"` element. If you set `aria-multiselectable="false"`, you'll experience behavior akin to Downshift. But honestly, the Downshift behavior seems buggy and inconsistent.

**Comment by emlai** [comment]
Hmm, if the second "selected" really is announcing the focus state, then that seems kinda redundant in the sense that if VoiceOver is announcing a menu item, doesn't that already means it's focused 🤔 

But yeah, adding `aria-multiselectable="true"` to the Downshift combobox reproduces the same issue, so I'm fine with closing this as a VoiceOver bug/expected behavior. Thanks!
