### ISSUE TITLE
Error message from Combobox with type="email"

### ISSUE THREAD

**Issue by asbjorn-brevio** [ariakit/ariakit#3086]
### Current behavior

When `Combobox` is used with `type="email"` (or `render={<input type="email" />}`), ariakit throws an error apparently on each keystroke:

```
Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('email') does not support selection.
```

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/p/sandbox/heuristic-burnell-dr7sw8
2. Type any letter into the input field
3. See error overlay, or console logs

### Expected behavior

No error when typing into input field

### Workaround

https://github.com/ariakit/ariakit/issues/3086#issuecomment-1824557156

**Comment by diegohaz** [comment]
Thanks for reporting. You can work around that using the [`setValueOnChange`](https://ariakit.org/reference/combobox#setvalueonchange) prop:

```jsx
const store = useComboboxStore();

<Combobox
  store={store}
  type="email"
  // TODO: Remove when https://github.com/ariakit/ariakit/issues/3086 is fixed
  setValueOnChange={(event) => {
    store.setValue(event.target.value);
    return false;
  }}
/>
```

**Comment by asbjorn-brevio** [comment]
Oh ok! Thank you 🤩

**Comment by renatorib** [comment]
I was trying a workaround where we change to `type="text"` before execute `setSelectionRange`, then back it to `type="email"` later, but seems to not work either.

It seems the element lost the state right after it turns back to email again.
![image](https://github.com/ariakit/ariakit/assets/3277185/fb01e11e-5fdb-446b-b600-67d5de449210)

Also, found this:
> Note that according to the [WHATWG forms spec](https://html.spec.whatwg.org/multipage/forms.html#concept-input-apply) selectionStart, selectionEnd properties and setSelectionRange method apply only to inputs of types text, search, URL, tel and password.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange

By now I think the only solution is check if element's type is supported to use setSelectionRange, and noop otherwise until we find a workaround. At least It will prevent errors to be throwed.
