### ISSUE TITLE
Tooltip should not use role and aria-describedby

### ISSUE THREAD

**Issue by ciampo** [ariakit/ariakit#3242]
### Current behavior

Mostly reporting @afercia ' s words:

>  the ARIA tooltip pattern is still under discussion in teh W3C groups as there is no agreement on its implementation. We should not use it for now. The ariakit implementation has problems in at least tow aspects:
> - it sets a tabindex=0 to non-natively focusable elements when they get a tooltip. that's very arguable. For axeample, a div element with a tooltip becomes focusable. That is just wrong.
> - it sets aria-describedby dynamically, which is arguable,

Source: https://github.com/WordPress/gutenberg/issues/57157#issuecomment-1865981198

### Steps to reproduce the bug

Interact with the Tooltip component across examples on the site

### Expected behavior

I guess that is mostly the point of this conversation — what roles and attributes should the `Tooltip` component use as of 2023, given the current state of the specs?

### Workaround

```jsx
<>
  <TooltipAnchor aria-describedby={undefined} />
  <Tooltip role={undefined} />
</>
```

**Comment by diegohaz** [comment]
The Tooltip component follows the [ARIA 1.2 spec](https://www.w3.org/TR/wai-aria-1.2/#tooltip):

> Authors SHOULD ensure that elements with the [role](https://www.w3.org/TR/wai-aria-1.2/#dfn-role) tooltip are referenced through the use of [aria-describedby](https://www.w3.org/TR/wai-aria-1.2/#aria-describedby) before or at the time the tooltip is displayed.

I'm not entirely sure I grasp how the `aria-describedby` attribute is dynamically set, and why it's a point of contention. If the concern is because the `aria-describedby` attribute is only applied when the tooltip is mounted, that's the best course of action since we can't reference an element that's not present in the DOM. By default, the tooltip remains persistent in the DOM. We could potentially consider a different approach when the [`unmountOnHide`](https://ariakit.org/reference/tooltip#unmountonhide) prop is in use.

However, both the `role` and `aria-describedby` attributes can be overwritten by the library using Ariakit:

```jsx
<>
  <TooltipAnchor aria-describedby={undefined} />
  <Tooltip role={undefined} />
</>
```

As for `tabindex`, all the [tooltip examples](https://ariakit.org/tags/tooltip) on the site render an accessible element as the anchor. We could highlight this more in the documentation. But given the headless nature of the library, I'm uncertain if we can impose any restrictions here. That could be handled in the higher-level component library or design system utilizing Ariakit. It's also something that automated accessibility testing tools should easily identify.

**Comment by afercia** [comment]
> The Tooltip component follows the [ARIA 1.2 spec](https://www.w3.org/TR/wai-aria-1.2/#tooltip):

That is about 'formal' compliance but, unfortunately, things in the reality are sometimes different. It's not a case that the ARIA Authoring Practices Guidelines do not provide an example of Tooltip implementation.
As I said, the `role=tooltip` is under ongoing discussion aa its purpose and implementation are unclear / subject to change.

DId you read the references I provided? Specifically:

**Clarify the use of role=tooltip #979**
https://github.com/w3c/aria/issues/979

In my opinion, an hyper-technical, formally-compliant approach to accessibility doesn't bring in any better user experience. A better approach would be pragmatically taking into consideration whether a specific implementation is any good for users.

Right now, the way the Tooltip component is used in WordPress Gutenberg is less than ideal. I do realize it's only in part due to ariakit and in part because of the way it is used in Gutenberg. However, the following example may help clarify. Screenshot:

![Screenshot 2023-12-22 at 09 53 30](https://github.com/ariakit/ariakit/assets/1682452/482e60c8-7313-47bd-8ef5-eb25939d0c4b)

- Originally, the Gutenberg Tooltip component was designed for only one case: to visually expose _the accessible name_ of icon buttons. It relied on the content of the `aria-label` attribute.
- The new ariakit-based implementation of the Tooltip component now adds an aria-describedby attribute, which basically uses the same content of the aria-label.
- As such, assistive technologies will get both the accessible name and the accessible description, which use basically the same content.
- In the example above, screen readers (with default settings) will announce the following:

`Color: Contrast slash Two {brief pause here} Contrast slash Two`

which is clearly less than ideal. 

**As it works now, the ariakit tooltip implementation leads developers to misuse it and the final result is a less than ideal user experience. I think this is the most important point, rather than formal compliance.** @cc Ciampo

The role=tooltip is essentially a description. A description should only be used for _additional, non-essential information_. It must not be used to provide the accessible name. As I mentioned in https://github.com/WordPress/gutenberg/issues/48222#issuecomment-1482937115

- It's perfectly fine revealing the accessible name on hover/focus by the means of a 'visual tooltip' **as long as it doesn't use a role=tooltip.** 
- The role=tooltip should only be used for a description. By its own nature, a description is additional, ancillary, non-essential information. There's no guarantee a description will actually be announced by screen readers as that depends on the user verbosity settings. 
- Also, all the considerations from [the ongoing discussion](https://github.com/w3c/aria/issues/979) in the W3C ARIA group still apply, which makes the usage of role=tooltip premature, at the very least. Even though it's in the ARIA 1.2 recommendation, its actual usefulness is arguable and I'd strongly recommend to just not use it.

**Comment by diegohaz** [comment]
@afercia, just to confirm and facilitate progress, you're proposing that the tooltip component in Ariakit should not use `role` and `aria-describedby`. Is this correct?

**Comment by atomiks** [comment]
So the only key difference is whether a "tooltip" is acting as a label or a description, right?

`aria-describedby` + `role="tooltip"` for additional, non-critical information.

```html
<button aria-describedby="a">Label</button>
<div id="a" role="tooltip">Description</div>
```

`aria-labelledby` with no role for a critical label.

```html
<button aria-labelledby="a"><icon /></button>
<div id="a">Label</div>
```

Perhaps `Tooltip` should actually be two different components, `TooltipDescription` and `TooltipLabel`, to be more intuitive for the user of the component. The latter is used as a universal alternative to `aria-label`, where it works for both sighted and non-sighted users.

If the developer keeps using `aria-label`, then the tooltip element is intended to be sighted only. That means there'd be no ARIA attributes added at all which would need an extra prop? Or, could it detect if the anchor already has `aria-label` and forgo adding the props?

**Comment by diegohaz** [comment]
I'm actually considering removing the `role="tooltip"` and `aria-describedby`/`aria-labelledby` attributes altogether, so the tooltip remains purely visual. It's not even a breaking change because those props are just implementation details.

**Comment by diegohaz** [comment]
The `aria-describedby` attribute was removed in #3318. This change should stop certain screen readers from announcing the label twice when a tooltip is applied to show the anchor's label, which is a common scenario. Now, the tooltip element is purely visual.

However, we didn't remove the `tooltip` role. Doing so would significantly affect our own examples (a clear sign that it could pose a major issue for others), especially since there's no other simple way to select the tooltip element in tests (users would need to use `data-testid` attributes or something similar).

If the `role="tooltip"` is still causing issues, it can be removed by the app as usual:

```jsx
<Tooltip role={undefined}>
```
