### ISSUE TITLE
Extra Unnecessary <span> Tag in Button Menu

### ISSUE THREAD

**Issue by Eldor901** [ariakit/ariakit#3342]
### Current behavior

I've noticed that there is an extra <span> tag within the button menu, which seems unnecessary. This issue leads to potential styling, functionality problems as it adds unnecessary complexity to the DOM structure.

### Steps to reproduce the bug

https://github.com/leviosa-medical/leviosa-app/assets/31973508/81e6e55d-b11e-4b14-bd3a-829f28c3d167

### Expected behavior

When the menu button is clicked, there should not be a <span> element following the button element.

### Workaround

https://github.com/ariakit/ariakit/issues/3342#issuecomment-1901338666

**Comment by diegohaz** [comment]
The video doesn't seem to be playing.

**Comment by Eldor901** [comment]
@diegohaz  take a look on screenshot 
<img width="1049" alt="image" src="https://github.com/ariakit/ariakit/assets/31973508/9d54a579-6ee1-4670-8342-aafcd9bd3e90">
`<span style="position: fixed;"></span>`

**Comment by GunnarSturla** [comment]
Thanks for a super quick reply diegohaz.

To give a better context for the issue we're looking at, we have a `ButtonGroup` component where we only want border radius on the first and last buttons. The structure would be something like this
```tsx
<div className="button-group">
  <Button>Btn 1</Button>
  <Button>Btn 1</Button>
</div>
```

The issue is that when the last button is a `MenuButton`, an extra `<span style="position: fixed"></span>` gets added after the (menu) `button` element. That breaks our css which sets the border radius somewhat like this, since the last element is now said `span`.

```css
.button-group :last-child {
  border-top-right-radius: 8px;
  border-bottom-right-radius: 8px;
}
```

To come back to the steps to reproduce, the video is going through the Menu example in the docs. In there we see the `button`  element for the `MenuButton` and a `div` for the `Menu` itself, but we also see an additional `span`. Here's the source code from the inspector
```html

  <button
    aria-expanded="true"
    aria-haspopup="menu"
    id=":Rb71bbrrqdsta:"
    class="button"
    type="button"
    aria-controls=":Rj71bbrrqdsta:"
  >
    Actions
    <span
      aria-hidden="true"
      style="width: 1em; height: 1em; pointer-events: none"
    >
      <svg
        display="block"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="1.5pt"
        viewBox="0 0 16 16"
        height="1em"
        width="1em"
      >
        <polyline points="4,6 8,10 12,6"></polyline>
      </svg>
    </span>
  </button>
  <span style="position: fixed"></span> <!-- This span -->
  <div>
    <div
      id=":Rj71bbrrqdsta:"
      data-dialog=""
      role="menu"
      tabindex="0"
      aria-orientation="vertical"
      class="menu"
      style="position: relative"
      aria-labelledby=":Rb71bbrrqdsta:"
      data-open="true"
      data-enter="true"
    >
      <!-- Menu contents -->
  </div>

```

I'm sure we could figure out a way to bypass this `span`, perhaps adding a `:nth-last-child(2):has(+ span)`, but that feels kinda hacky, so we were wondering what the purpose of it, and whether it could be avoided.

Thanks for your help, and thanks for a great library!

**Comment by diegohaz** [comment]
Thanks for providing additional context.

That component is part of the [`preserveTabOrderAnchor`](https://ariakit.org/reference/menu#preservetaborderanchor) feature. However, your bug report is valid because it shouldn't appear if the `Menu` doesn't use [`portal`](https://ariakit.org/reference/menu#portal).

In the meantime, you can specifically disable the [`preserveTabOrderAnchor`](https://ariakit.org/reference/menu#preservetaborderanchor) prop:

```jsx
<Menu
  // Remove when https://github.com/ariakit/ariakit/issues/3342 is resolved
  preserveTabOrderAnchor={null}
>
```

I also recommend using `:last-of-type` instead of `:last-child`, particularly if you plan to use this feature in the future.

**Comment by GunnarSturla** [comment]
Unfortunately we can't use `:last-of-type` since we might have a mix of different elements in there (e.g. a `button` and `a`) but the `preserveTabOrderAnchor` fix you suggested works well.

Thanks for your help

**Comment by diegohaz** [comment]
Alternatively, if you're interested in using the `preserveTabOrderAnchor` feature, you can assign a shared class to all items and use the `of <selector>` syntax on `:nth-last-child()`:

```css
.button-group :nth-last-child(1 of .item) {
  border-top-right-radius: 8px;
  border-bottom-right-radius: 8px;
}
```
