### ISSUE TITLE
Select: `defaultValue` doesn't behave as intended when using `unmountOnHide`

### ISSUE THREAD

**Issue by brookewp** [ariakit/ariakit#3374]
### Current behavior

When enabling `unmountOnHide` on the `SelectPopover`, if a `defaultValue` isn't defined, the `SelectButton` renders an empty string. 

### Steps to reproduce the bug

1. Open https://stackblitz.com/edit/wmpqxu?file=app%2Fselect%2Findex.tsx
2. View rendered Select component:

<img width="277" alt="Screenshot 2024-01-22 at 1 59 39 PM" src="https://github.com/ariakit/ariakit/assets/35543432/93d94125-6ba3-46fd-b21b-4a81c16c3251">

### Expected behavior

When a `defaultValue` isn't provided, the first non-disabled item should be used.

### Workaround

By using an explicitly defined `defaultValue`.

**Comment by diegohaz** [comment]
This one's a bit tricky because the `SelectItem` elements aren't rendered if the popover is unmounted. Consequently, Ariakit doesn't receive any information about the items from the React tree. Explicitly setting a `defaultValue` is the recommended approach, especially for server-side rendering.

This is a limitation of compound components as opposed to passing the options as props, where you'd have this information upfront.

**Comment by brookewp** [comment]
Thank you for the info and quick response! We will either make the prop required or add a fallback `defaultValue`.
