### ISSUE TITLE
Combobox setValue is called with empty when selectedValue changes

### ISSUE THREAD

**Issue by gylxan** [ariakit/ariakit#3580]
### Current behavior

Hi!

So our team built a Combobox component using the ariakit Combobox for using in other products. 
Our combobox accepts options with a value and a label property, where the label can be a ReactNode to customize the list of options, when rendering.

Due to this options format, we have to map the selected options to their values to match the `selectedValue` property of the `ComboboxProvider`. Also we want to filter on our own and limit the filtered options by using the `value` and `setSearchValue` properties.

This combination leads to the problem, that when you start typing in the `Combobox`, the filtered options are changing, a re-render is triggered, the `selectValue` property value is re-created and `setSearchValue` is called twice! Once with the typed character and afterwards with an empty string. So in the end, we can't type!

### Steps to reproduce the bug

1. Open https://codesandbox.io/p/devbox/infallible-bohr-khzxhn-27pjgx
2. Type in anything for filtering
3. Filter not working
4. Remove `selectedValue` in Combobox.tsx
5. Filtering is no working

### Expected behavior

Changing the `selectedValue` does not call `setValue` with empty string

### Workaround

https://github.com/ariakit/ariakit/issues/3580#issuecomment-1994042551

**Comment by diegohaz** [comment]
This occurs because [`resetValueOnSelect`](https://ariakit.org/reference/combobox-provider#resetvalueonselect) is automatically set to `true` in [`ComboboxProvider`](https://ariakit.org/reference/combobox-provider) when the [`selectedValue`](https://ariakit.org/reference/combobox-provider#selectedvalue) is an array. The reset is triggered when the array is updated. You can manually disable this prop if you prefer:

```jsx
<ComboboxProvider resetValueOnSelect={false}>
```

Alternatively, you can memoize the value passed to the [`selectedValue`](https://ariakit.org/reference/combobox-provider#selectedvalue) prop within your `Combobox` component:

```jsx
  const selectedValues = useMemo(
    () => selected.map((option) => option.value),
    [selected],
  );

  <ComboboxProvider selectedValue={selectedValues}>
```

But this requires that the consumers of your `Combobox` component also memoize the `selected` value, which you're already doing in your example, though I suppose you can't guarantee that.

**Comment by gylxan** [comment]
I wasn't aware, that `resetValueOnSelect` is `true` per default. Works like a charm, when setting it to `false`! 

Thank you @diegohaz 🙏

**Comment by diegohaz** [comment]
Great! I'm closing this issue as I don't believe there's anything we can address in the library. Ideally, users should memoize those non-primitive values themselves.
