### ISSUE TITLE
`focus()` method of elements called without `focusVisible: true`

### ISSUE THREAD

**Issue by kripod-wise** [ariakit/ariakit#3815]
### Current behavior

Working with `SelectLabel`, I noticed the behavior of that component differs from what a native `label` element does. When the former is clicked by mouse, the associated `Select` gets a focus outline, despite _not_ using keyboard navigation.

### Steps to reproduce the bug

1. Open https://stackblitz.com/edit/ariakit-mt1hf4?file=src%2FApp.tsx
2. Try clicking the label and then outside over and over by mouse
3. Notice the focus ring appearing inadvertently, unlike when using a native `<label>`:

   <img width="362" alt="image" src="https://github.com/ariakit/ariakit/assets/92147789/e37ca749-39c7-49e7-85ef-1de3b9083eb2">

### Expected behavior

When clicking an Ariakit Label component (e.g. `SelectLabel`) using a pointer, I’d expect the focus outline not to be visible, in contrast to the keyboard-activated behavior, to match native element semantics.

### Possible solutions

Specify `{ focusVisible: true }` as an option possibly for most HTMLElement.focus() calls, unless there’s a strong reason not to on a per-scenario basis.

**Comment by diegohaz** [comment]
I'm not sure we can prevent the browser from adding the `focus-visible` state to an element when it gets programmatically focused. Even the upcoming [`focusVisible`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#focusvisible) option doesn't seem to support this:

> By default, or if the property is not `true`, a browser may still provide visible indication if it determines that this would improve accessibility for users.

That's why we started recommending using our own [`data-focus-visible`](https://ariakit.org/guide/styling#data-focus-visible) attribute as a selector instead.

**Comment by kripod** [comment]
Thanks for responding. Indeed the docs suggest that, although in my experience so far, adding `focusVisible: true` explicitly has mitigated similar issues most of the time, at least in Chrome.

**Comment by diegohaz** [comment]
Also, a native select element will always get the native `focus-visible` state, similar to textbox elements, even when clicking on its label. Because of that, we always apply the `data-focus-visible` attribute to the `Select` component when used within a form.

**Comment by kripod** [comment]
`:focus-visible` styles should be alright to have. I just want to avoid triggering plain `:focus` ones when the focus change is possibly initiated by a pointer event instead of keyboard navigation.

The reason for preferring `focus-visible: true` is that I wouldn’t want to roll any custom outline styling for some of my projects, so that users would be familiar with the UA style applied by the browser they use. (Browsers tend to have accessible outlines by default nowadays.)

**Comment by diegohaz** [comment]
> `:focus-visible` styles should be alright to have. I just want to avoid triggering plain `:focus` ones when the programmatic focus change is possibly initiated by a pointer event instead of keyboard navigation.

I'm not sure I follow. AFAIK, all `:focus-visible` is `:focus`, but not all `:focus` is `:focus-visible`.

**Comment by kripod** [comment]
I might be wrong, but I thought `:focus-visible` is only applied when triggered by keyboard navigation, while `:focus` is applied regardless of the initiator. So `:focus` is like a broader variant of `:focus-visible`.

Therefore, relying upon the latter (which is the default behavior of `element.focus()`) could be a minor annoyance for pointer users, as they needn’t rely upon focus outlines for their interactions.

**Comment by kripod** [comment]
Thanks for your in-depth explanation, all of that makes a lot of sense. Please consider this a non-issue 😊
