### ISSUE TITLE
[Dialog] - when `autoFocusOnShow` doesn't work with`unmountOnHide`

### ISSUE THREAD

**Issue by ItaiYosephi** [ariakit/ariakit#4055]
### Current behavior

When setting `unmountOnHide` to `true`, the first tabable element doesn't get the focus.

https://github.com/user-attachments/assets/7347572e-a44f-4f4b-844c-f824eb7b4235

### Steps to reproduce the bug

1. Open https://stackblitz.com/edit/bk14dv?file=dialog%2Findex.tsx
2. open the dialog

### Expected behavior

First button should be focused

**Comment by benrodrs** [comment]
This seems to be an issue with the Radix `ToggleGroup` component, not Ariakit. Does it work if you use the Radix `Dialog` instead?

**Comment by ItaiYosephi** [comment]
> This seems to be an issue with the Radix `ToggleGroup` component, not Ariakit. Does it work if you use the Radix `Dialog` instead?

Why does it work when `unmountOnHide={false}` then?
the group has `tabindex="0"`, ariakit should apply focus to the first tabable element

**Comment by benrodrs** [comment]
> > This seems to be an issue with the Radix `ToggleGroup` component, not Ariakit. Does it work if you use the Radix `Dialog` instead?
> 
> Why does it work when `unmountOnHide={false}` then? the group has `tabindex="0"`, ariakit should apply focus to the first tabable element

I don't have much knowledge of Radix internals, but I suspect it defaults to `tabindex="-1"` and `tabindex="0"` is added only after the first render, which is why it works without `unmountOnHide` (it has enough time to add `tabindex="0"`). You can confirm this by manually passing `tabIndex={0}` to the first item, which should override the Radix default value.

I quickly tested your repro with the Radix Dialog, and the behavior is the same (since Radix seems to default to unmounted).

If you try it with any composite component from Ariakit, like `Toolbar`, you'll get the expected behavior since Ariakit defaults all composite items to `tabindex="0"` and only then enables roving tabindex. This is necessary because keyboard users might need to access roving tabindex widgets before JavaScript kicks in. If it defaults to `tabindex="-1"` like Radix apparently does, keyboard users won't be able to navigate to those elements before JavaScript finishes loading.

We have a specific test for the above scenario:

https://github.com/ariakit/ariakit/blob/fc012ab2137e267c77774b845ab830e16727a69f/examples/toolbar/test-chrome-js-disabled.ts#L9-L18

**Comment by ItaiYosephi** [comment]
@benrodrs Thanks for the quick response, it does seems like an issue with Radix
