### ISSUE TITLE
Composite: react to updates in the registered items

### ISSUE THREAD

**Issue by ciampo** [ariakit/ariakit#4129]
### Motivation

When using `Composite`, it's not uncommon that `CompositeItem` components can get added / removed / mutated at render time; for example:

- the currently active item is removed from the react tree;
- the currently active item is disabled;
- the active id doesn't initially match any options, but an option with the active ID is added later at render time;

While `Composite` handles the initial selection of an active item, it doesn't seem to handle any of the above cases, which can result in some unfortunate scenarios, including the inability of the end user to focus any item in the composite widget.

It would be great for consumers of `Composite` (and derived components) if some (or all) of those scenarios were handled by the component itself, since they are edge cases that can cause the component to stop working as expected.

### Usage example

https://stackblitz.com/edit/thqfra?file=button%2Findex.tsx&theme=dark

Note that, when the active composite item is removed from the react tree, the active id can become stale, causing Composite to skip focus on its items entirely.

https://github.com/user-attachments/assets/4f58e7a3-bcff-40d5-92e0-3552849eaee9

### Requirements

`Composite` (and `Composite`-based components) should offer a way for consumers to opt-in to the component updating the `activeId` when the currently active id doesn't match a focussable composite item, similarly to what the component already does on initial render.

### Workaround

The workaround is to implement this custom logic in consumer-land, which is not convenient and requires the consumer to re-write the same logic every time.

Examples:
- [updated version of the demo shared above](https://stackblitz.com/edit/thqfra-cjqa3f?file=button%2Findex.tsx&theme=dark) posted above that resets the active ID when the element is removed;
- [handling of such edge cases in the `Tabs` component in `@wordpress/components`](https://github.com/WordPress/gutenberg/blob/609a3c8d38a0608b41b1827ec4a8c1f812487ef2/packages/components/src/tabs/index.tsx#L55-L192)

Or https://github.com/ariakit/ariakit/issues/4129#issuecomment-2367928139

### Possible implementations

https://github.com/ariakit/ariakit/issues/4129#issuecomment-2367928139

**Comment by ciampo** [comment]
cc @DaniGuardiola who had also brought this up some time ago when reviewing `Tabs` code in `@wordpress/component`

**Comment by diegohaz** [comment]
> * the currently active item is removed from the react tree;
> * the currently active item is disabled;

The issue is that an element being removed from the DOM doesn't necessarily mean it's no longer available. For instance, third-party virtualization libraries might temporarily remove the active element when it's offscreen. I've also seen situations where React Suspense temporarily removes an element from the DOM. There could be other cases I'm not aware of.

An idea I had was to create a `Disposable` module to manage cases where the currently focused element is disabled or removed from the DOM. This would include composite widget cases (`activeId`) and scenarios like an array field in a form where deleting a row also removes the button itself, in which case we could automatically move focus to the next or previous row.

> * the active id doesn't initially match any options, but an option with the active ID is added later at render time;

I'd expect it to work already: https://stackblitz.com/edit/j6zscv?file=toolbar%2Fstyle.css,toolbar%2Ficons.tsx,toolbar%2Findex.tsx&theme=dark

Do you have an example where that's not the case?

**Comment by diegohaz** [comment]
Related: https://github.com/ariakit/ariakit/issues/3232#issuecomment-1863533666

**Comment by ciampo** [comment]
> The issue is that an element being removed from the DOM doesn't necessarily mean it's no longer available. For instance, third-party virtualization libraries might temporarily remove the active element when it's offscreen. I've also seen situations where React Suspense temporarily removes an element from the DOM. There could be other cases I'm not aware of.

That's why this could be an opt-in behaviour.

Also, I guess it would make sense especially when the component in uncontrolled. When it's controlled, there could be an assumption that the consumer is in charge of keeping the value of `activeId` up to date?

> An idea I had was to create a `Disposable` module to manage cases where the currently focused element is disabled or removed from the DOM. This would include composite widget cases (`activeId`) and scenarios like an array field in a form where deleting a row also removes the button itself, in which case we could automatically move focus to the next or previous row.

This could be an idea, but currently a bit too abstract for me (given that I don't know well all of ariakit's internals).

> > * the active id doesn't initially match any options, but an option with the active ID is added later at render time;
> 
> I'd expect it to work already: [stackblitz.com/edit/j6zscv?file=toolbar%2Fstyle.css,toolbar%2Ficons.tsx,toolbar%2Findex.tsx&theme=dark](https://stackblitz.com/edit/j6zscv?file=toolbar%2Fstyle.css,toolbar%2Ficons.tsx,toolbar%2Findex.tsx&theme=dark)
> 
> Do you have an example where that's not the case?

You're right that it works in your demo, but there's also a cost to pay — that the composite widget is not focussable until the "Redo" button is added to the DOM

**Comment by diegohaz** [comment]
> > > * the active id doesn't initially match any options, but an option with the active ID is added later at render time;
> > 
> > 
> > I'd expect it to work already: [stackblitz.com/edit/j6zscv?file=toolbar%2Fstyle.css,toolbar%2Ficons.tsx,toolbar%2Findex.tsx&theme=dark](https://stackblitz.com/edit/j6zscv?file=toolbar%2Fstyle.css,toolbar%2Ficons.tsx,toolbar%2Findex.tsx&theme=dark)
> > Do you have an example where that's not the case?
> 
> You're right that it works in your demo, but there's also a cost to pay — that the composite widget is not focussable until the "Redo" button is added to the DOM

Sure, that's a contrived example. If you have a realistic scenario where Ariakit doesn't work as expected (in the context of `the active id doesn't initially match any options, but an option with the active ID is added later at render time`), I'm happy to take a look.

**Comment by ciampo** [comment]
> Sure, that's a contrived example. If you have a realistic scenario where Ariakit doesn't work as expected (in the context of `the active id doesn't initially match any options, but an option with the active ID is added later at render time`), I'm happy to take a look.

I believe I had seen such a edge case in the Gutenberg editor, but that was some time ago. Probably this scenario is the least high priority.

But your demo proves that if a consumer sets an `activeId` that doesn't exist, the whole widget becomes unfocussable. Should there be a way to avoid this ? It can potentially break the whole experience for assistive technology users

**Comment by diegohaz** [comment]
> But your demo proves that if a consumer sets an `activeId` that doesn't exist, the whole widget becomes unfocussable. Should there be a way to avoid this ? It can potentially break the whole experience for assistive technology users

My point is that without a real use case, we can't determine if this is an actual problem. Without something to test against, it's easy to come up with the wrong solution. My demo only shows the current behavior and isn't representative of a real-world scenario.

A real use case would be, for example, setting the default active id of a composite widget inside a dialog or popup before it opens. In this situation, there's no issue since the composite widget isn't accessible yet.

**Comment by benrodrs** [comment]
Perhaps we can make all composite items tabbable if the current active id is not rendered, similar to how we make all items tabbable before hydration:

https://github.com/ariakit/ariakit/blob/4acdb60379a8cf80949bb882c99fe438ac36cf34/packages/ariakit-react-core/src/composite/composite-item.tsx#L394-L398

**Comment by ciampo** [comment]
Real scenarios that we encountered:
- https://github.com/WordPress/gutenberg/issues/65283
- the cases that [`Tabs`'s internal code](https://github.com/WordPress/gutenberg/blob/609a3c8d38a0608b41b1827ec4a8c1f812487ef2/packages/components/src/tabs/index.tsx#L55-L192) covers

**Comment by diegohaz** [comment]
> Perhaps we can make all composite items tabbable if the current active id is not rendered, similar to how we make all items tabbable before hydration:
> 
> https://github.com/ariakit/ariakit/blob/4acdb60379a8cf80949bb882c99fe438ac36cf34/packages/ariakit-react-core/src/composite/composite-item.tsx#L394-L399
> 
> Easy way to test this in userland:
> 
> ```js
> function CompositeItem(props: Ariakit.CompositeItemProps) {
>   const store = Ariakit.useCompositeContext();
> 
>   const tabbable = Ariakit.useStoreState(store, (state) => {
>     return !store?.item(state?.activeId)?.element?.isConnected;
>   });
> 
>   return <Ariakit.CompositeItem tabbable={tabbable} {...props} />
> }
> ```

This seems like a good general solution for all cases.

I'm not entirely sure `element?.isConnected` will always be in sync with the DOM, though. This `useStoreState` callback runs only when the host component (`CompositeItem`) re-renders or when the store state updates. If the component is not re-rendered (e.g., it's memoized or isn't affected by the update that triggered the active item to be disconnected) or the store state doesn't update when an element is disconnected from the DOM, this will be out of sync. But I don't even know if this is possible (just thinking out loud).

@ciampo, would you be willing to try this in userland before we implement here?

> Real scenarios that we encountered:
> 
> * [Options in the CircularOptionPicker may be not operable with the keyboard WordPress/gutenberg#65283](https://github.com/WordPress/gutenberg/issues/65283)
> * the cases that [`Tabs`'s internal code](https://github.com/WordPress/gutenberg/blob/609a3c8d38a0608b41b1827ec4a8c1f812487ef2/packages/components/src/tabs/index.tsx#L55-L192) covers

Thanks! I'm aware of those, but it seems the issue is more about these two points:

> * the currently active item is removed from the react tree;
> * the currently active item is disabled;

But the third point:

> * the active id doesn't initially match any options, but an option with the active ID is added later at render time

is actually a side effect of trying to address the other two, so it should be handled separately. I mean, if you update `activeId` whenever it changes and there's no matching DOM element, you lose the ability to lazily render the matching element. It's a valid point, but I don't think it's related to the current behavior of the library.

**Comment by ciampo** [comment]
I'll take a look and maybe give it a try in the context of https://github.com/WordPress/gutenberg/issues/65283
