### ISSUE TITLE
Body scroll should be enabled only after the animation ends

### ISSUE THREAD

**Issue by diegohaz** [ariakit/ariakit#885]
### Discussed in https://github.com/reakit/reakit/discussions/883

<div type='discussions-op-text'>

<sup>Originally posted by **dmwin72015** June 27, 2021</sup>
when the dialog leave, the padding-right of the body was removed, resulting in a slight movement of the page

It might be better to allow the page to scroll after the animation ends</div>

**Comment by Grsmto** [comment]
@hamidKMB actually I think that's already how the `animating` prop is working on Reakit, with `onAnimationEnd`.

@diegohaz is there anything blocking this change to happen? I just tried it in a fork and the fix you suggested works fine!
Let me know if there is any edge case that you're aware of, otherwise I can PR with the change.
Thanks!

**Comment by diegohaz** [comment]
Closing as this is fixed in v2.

If someone needs this fix on v1, please submit a PR against the v1 branch.
